/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Arrow;

import Flats.FlatHandler;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M_Ibrahiem
 */
public class viewArrow extends javax.swing.JFrame {
String sele;
    /**
     * Creates new form viewArrow
     */
    public viewArrow() throws SQLException {
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        showPCom();
        
    }

    public long calcExp() throws SQLException
    {
        arrowhandler h = new arrowhandler();
        
        Vector returnV = h.showComProject(sele);
         long n=0;
         for(int i=0 ; i< returnV.size() ; i++)
         {
             n += Long.valueOf(returnV.elementAt(i).toString()) ;
         }
                
         return n;
                }
    public long calcProfit() throws SQLException
    {
        arrowhandler h = new arrowhandler();
        
        Vector returnV = h.showProfit(sele);
         long n=0;
         for(int i=0 ; i< returnV.size() ; i++)
         {
             n += Long.valueOf(returnV.elementAt(i).toString()) ;
         }
                
         return n;
                }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        out = new javax.swing.JLabel();
        inLab1 = new javax.swing.JLabel();
        inLab2 = new javax.swing.JLabel();
        in = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        arrow = new javax.swing.JLabel();
        asd = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setTitle("الأسعار للأسهم");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("الربح");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("سعر السهم");

        out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out.setText("0");

        inLab1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inLab1.setText("الداخل");

        inLab2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inLab2.setText("الخارج");

        in.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        in.setText("0");

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setText("0");

        arrow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arrow.setText("0");

        asd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("اختر رقم المشروع :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(asd, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(inLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(out)
                        .addGap(58, 58, 58)
                        .addComponent(total)
                        .addGap(26, 26, 26)
                        .addComponent(arrow))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(inLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asdActionPerformed
 
        sele = asd.getSelectedItem().toString();
        try {
         in.setText(calcProfit()+"");
        out.setText(calcExp()+"");
       total.setText(calcProfit()-calcExp()+"");
     arrow.setText(((calcProfit()-calcExp())/24)+"");
        } catch (SQLException ex) {
             }
    }//GEN-LAST:event_asdActionPerformed
private void  showPCom() throws SQLException{
    
arrowhandler f=new arrowhandler();
     
            Vector pp=f.showComP();
            for(int i=0;i<pp.size();i++){
            
            asd.addItem(pp.elementAt(i).toString());
            }
           
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewArrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewArrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewArrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewArrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new viewArrow().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(viewArrow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow;
    private javax.swing.JComboBox<String> asd;
    private javax.swing.JLabel in;
    private javax.swing.JLabel inLab1;
    private javax.swing.JLabel inLab2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel out;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
