/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package onwner;

import Amount.AmountHandler;
import Database.DB_Connection;
import Flats.FlatHandler;
import Profits.profitHandler;
import Projects.insertProj;
import java.awt.ComponentOrientation;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author M_Ibrahiem
 */
public class InsertOwner extends javax.swing.JFrame {

    /**
     * Creates new form InsertOwner
     */
    public InsertOwner() throws SQLException {
             this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
         showPCom2(); 
     oname2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
   
    }
    String Pro_num;
 private void  showPCom2() throws SQLException{
    
          OwnerHandler f=new OwnerHandler();
     
            Vector pnum2=f.showComProject();
            for(int i=0;i<pnum2.size();i++){
            
            ins_am.addItem((String) pnum2.elementAt(i));
            }
           
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        oname2 = new javax.swing.JTextField();
        addb = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pchos2 = new javax.swing.JComboBox();
        ins_am = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setTitle("اضافة ملاك");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("اسم المالك: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("رقم الهاتف: ");

        addb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addb.setText("إضافة");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewOwner(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("رقم الشقة :");

        pchos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pchos2ActionPerformed(evt);
            }
        });

        ins_am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_amActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("اختر رقم المشروع :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oname2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pchos2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ins_am, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_am, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oname2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pchos2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void  showOCom() throws SQLException{
    
 OwnerHandler f=new OwnerHandler();
     
            Vector pnum=f.showComFlats(Pro_num);
            for(int i=0;i<pnum.size();i++){
            
            pchos2.addItem(pnum.elementAt(i));
            }}
 private void p(String msg)
    {
        JOptionPane.showMessageDialog(null, msg);
    }  
  
    private void addnewOwner(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewOwner
 try {
            String oname , phone , pfname,pn;
             
            oname = oname2.getText();
            phone = phone2.getText();
           pfname=pchos2.getSelectedItem().toString();    
            int  PH;
      
              pn=ins_am.getSelectedItem().toString();
          PH = Integer.parseInt(phone);
           
            DB_Connection db=new DB_Connection();
            Statement st;
            int rows;
            
            Connection co = db.conect();         
              String sql="insert into OWNER(PHONE,ONAME,PFNUM,PNUM)VALUES("+PH+",'"+oname+"','"
                      +pfname+"','"+pn+"')";
                st = co.createStatement();
                rows = st.executeUpdate(sql);
                co.commit();
          
              st.close(); 
                 if(rows>0)
            {
                JOptionPane.showMessageDialog(null, "تم الإدخال بنجاح");
            }
            else{
                JOptionPane.showMessageDialog(null, "هناك مشكلة فى عملية الإدخال ");
            }
                  
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "هناك مشكلة في قاعده البيانات");
        }
        catch(NullPointerException n)
         {
             JOptionPane.showMessageDialog( null, "لا يوجد بيانات");
         }
        catch(NumberFormatException nu)
         {
             JOptionPane.showMessageDialog( null,"يجب ادخال البيانات بطريقة صحيحة");
         }
               
     
                              

    }//GEN-LAST:event_addnewOwner

    private void ins_amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_amActionPerformed
     Pro_num = ins_am.getSelectedItem().toString();
        try {
            pchos2.removeAllItems();
            showOCom();
        } catch (SQLException ex) {
            Logger.getLogger(InsertOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ins_amActionPerformed

    private void pchos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pchos2ActionPerformed
      
    }//GEN-LAST:event_pchos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertOwner().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertOwner.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addb;
    private javax.swing.JComboBox<String> ins_am;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField oname2;
    private javax.swing.JComboBox pchos2;
    private javax.swing.JTextField phone2;
    // End of variables declaration//GEN-END:variables
}
