/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package onwner;

import Flats.FlatHandler;
import Flats.ShowFlats;
import Profits.profitHandler;
import Projects.ProjectHandler;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projcet_partner.showProjPartner;

/**
 *
 * @author M_Ibrahiem
 */
public class ShowOwner extends javax.swing.JFrame {

    /**
     * Creates new form ShowOwner
     */
    public ShowOwner() throws SQLException {
             this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        setTitle("عرض الملاك");
    fillOwner();
    showPCom();
    }
    String sale;
     private void  showPCom() throws SQLException{
    
profitHandler f=new profitHandler();
     
            Vector pp=f.showComP();
            for(int i=0;i<pp.size();i++){
            
            jComboBox1.addItem(pp.elementAt(i).toString());
            }
           
}
private void fillOwner() throws SQLException{
 DefaultTableModel modle =(DefaultTableModel)ownerTab.getModel();
 modle.setRowCount(0);
 
     OwnerHandler ff=new OwnerHandler();
     Vector flat=ff.ownerShow(sale);
       
       for(int i=0;i<flat.size();i++){
         Vector list=(Vector) flat.elementAt(i);
           
        modle.addRow(list);  
       }
 }
private void p(String msg){
   {
        JOptionPane.showMessageDialog(null, msg);
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnTab = new javax.swing.JScrollPane();
        ownerTab = new javax.swing.JTable();
        edb = new javax.swing.JButton();
        prb = new javax.swing.JButton();
        prinb = new javax.swing.JButton();
        delb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setTitle("عرض الملاك");

        ownerTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "الاسم", "رقم الهاتف", "رقم الشقه والمشروع"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OnTab.setViewportView(ownerTab);

        edb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edb.setText("تعديل");
        edb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edbActionPerformed(evt);
            }
        });

        prb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prb.setText("اضافه");
        prb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOw(evt);
            }
        });

        prinb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prinb.setText("طباعة");
        prinb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prinbActionPerformed(evt);
            }
        });

        delb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delb.setText("حذف");
        delb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delOwner(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("تحديث البيانات");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("اختر رقم المشروع :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OnTab)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(edb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(prb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prinb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(OnTab, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(prinb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prinbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prinbActionPerformed
        try {
            boolean b = ownerTab.print();        // TODO add your handling code here:
        } catch (PrinterException ex) {
            
            String printMsg ="عملية الطباعة لم تتم بنجاح";
             p(printMsg);
        }
    }//GEN-LAST:event_prinbActionPerformed

    private void addOw(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOw
        try {
            InsertOwner i=new InsertOwner();
            i.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ShowOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addOw

    private void delOwner(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delOwner
        try {
            DeleteOwner d=new DeleteOwner();
            d.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ShowOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delOwner

    private void edbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edbActionPerformed
        try {
            EditOw ed=new EditOw();
            ed.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ShowOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
            this.fillOwner();
            
        } catch (SQLException ex) {
            Logger.getLogger(showProjPartner.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        sale = jComboBox1.getSelectedItem().toString();
        try {
               fillOwner();
        } catch (SQLException ex) {
            Logger.getLogger(ShowFlats.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowOwner().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ShowOwner.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane OnTab;
    private javax.swing.JButton delb;
    private javax.swing.JButton edb;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable ownerTab;
    private javax.swing.JButton prb;
    private javax.swing.JButton prinb;
    // End of variables declaration//GEN-END:variables
}
